version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/docs"
    schedule:
      interval: "daily"    
    groups:
      docusaurus:
        patterns:
          - "*docusaurus*"
  - package-ecosystem: "nuget"
    directory: "/"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    groups:
      test-dependencies:
        patterns:
          - NUnit*
          - "*Test*"
      modularpipelines-dependencies:
        patterns:
          - "*ModularPipeline*"
    ignore:
      - dependency-name: "Microsoft.Extensions.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "Microsoft.CodeAnalysis.*"
      - dependency-name: "Microsoft.Bcl.*"
